### ISSUE TITLE
Cancel button?

### ISSUE THREAD

**Issue by rsimenok** [SugarAndCandy/SCPinViewController#1]
How can i refuse from setting password? :)

**Comment by makleso6** [comment]
@rsimenok use navigation controller

**Comment by sergpol** [comment]
"use navigation controller" - it's true, but only for the PIN code creation mode. But if you need to reset the PIN code because the user forgot it? The request for PIN code in this case opens in full screen mode, and here you need the "Forgot PIN code?" Button, on which I could hang the exit function from the application profile. Otherwise, user can just delete and reinstall the application.
Thank you in advance!
